In [47]:
# import numpy package as np
import numpy as np

## First Task

In [49]:
# firstly, create two arrays 'a' and 'b'
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
# use np.itersect1d function to find the distinct values between array a and b and give the value to first
first = np.intersect1d(a, b)
# print the result
print(first)


[2 4]


## Second Task

In [50]:
# Firstly, use np.arange to create an array in a sequencing range from 1 to 15
# secondly, use reshape(3,5) to reshape the array to 3*5 sequence
# finally, use .T to reshape the array to 5*3 sequence and give the values to a
a = np.arange(1,16).reshape(3,5).T
# pirint the result
print(a)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


## Third Task

In [51]:
# firstly, create two arrays 'a' and 'b'
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
# use np.itersect1d function to find the distinct values between array a and b and give the value to temp
temp = np.intersect1d(a, b)
# create a interation, if the element in array a is in temp, then skip that element, 
# only get the element which is not present in array b.
# which means remove temp's value from array a
for i in range(len(temp)):
    a = a[a!=temp[i]]
# print the result    
print(a)

[ 7 15  1  8]


## Fourth Task

#### Firstly, use google to find the distance between nyc to key west, which is 1443 miles
#### Secondly, use np.random.randint(30,1443,35), which means generate 35 random integer numbers, the range is 1 to 1443.
#### Thirdly, use np.sort function, so the result will be cumulative miles of the recorded each day during the trip
#### Next, we also need at least 4 non-consecutive days, so we can use a[n] = a[n+1], to make two days miles become the same and we need to do a[34] = 1443, which meas the last day will be complete 1443 miles.
#### Next, we use np.diff(a) funciton to get the total miles that you rode each day, but the problem is, this function will lost the first value,  so I create a new array 'aa', and give the first day value to it, (aa = a[0]).
#### finally, we combine these two arrays, to get the complete total miles that you rode each day.

In [122]:
# create a new array to store values, 
# and use np.random.randint to generate 35 random integer numbers, the range is 1 to 1443
a=np.random.randint(1,1443,35)
#use np.sort function to sort array a
a=np.sort(record)
# we need at least 4 non-consecutive days, so we do a[10] = a[11]...to make two days miles become the same
a[10]=a[11]
a[16]=a[17]
a[26]=a[27]
a[31]=a[32]
# after sorted this array, we need to make sure the last day of trip will complete 1443 miles
# so we do record[34]=1443
a[34]=1443
# print cumulative miles you recorded each day during your trip
print('cumulative miles: ',a)
# create a new array 'new' and use np.diff(a) function to get the total miles that you rode each day(miss first value)
new = np.diff(a)
#create a new array 'aa' and give the first value of array a to 'aa', aa = a[0]
aa = a[0]
#use np.append combine these two array to get the complete total miles that you rode each day
each_day = np.append(aa,new)
#print the total miles that you rode each day
print('each day:',each_day)

cumulative miles:  [  16   66   88  173  180  181  242  256  263  313  346  346  391  425
  438  500  554  554  649  704  708  727  842  879  907  985 1041 1041
 1168 1187 1204 1327 1327 1354 1443]
each day: [ 16  50  22  85   7   1  61  14   7  50  33   0  45  34  13  62  54   0
  95  55   4  19 115  37  28  78  56   0 127  19  17 123   0  27  89]


## Fifth Task

In [123]:
import pandas
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').as_matrix()

# verify you have an ndarray object
type(nyc_water)
#print nyc_water
nyc_water

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


array([[   1979. , 7102100. ,    1512. ,     213. ],
       [   1980. , 7071639. ,    1506. ,     213. ],
       [   1981. , 7089241. ,    1309. ,     185. ],
       [   1982. , 7109105. ,    1382. ,     194. ],
       [   1983. , 7181224. ,    1424. ,     198. ],
       [   1984. , 7234514. ,    1465. ,     203. ],
       [   1985. , 7274054. ,    1326. ,     182. ],
       [   1986. , 7319246. ,    1351. ,     185. ],
       [   1987. , 7342476. ,    1447. ,     197. ],
       [   1988. , 7353719. ,    1484. ,     202. ],
       [   1989. , 7344175. ,    1402. ,     191. ],
       [   1990. , 7335650. ,    1424. ,     194. ],
       [   1991. , 7374501. ,    1469. ,     199. ],
       [   1992. , 7428944. ,    1369. ,     184. ],
       [   1993. , 7506166. ,    1368.5,     182. ],
       [   1994. , 7570458. ,    1357.7,     179. ],
       [   1995. , 7633040. ,    1325.7,     174. ],
       [   1996. , 7697812. ,    1297.9,     169. ],
       [   1997. , 7773443. ,    1205.5,     1

In [124]:
#1 What is the maximum yearly NYC consumption of water in millions of gallons per day?
# use nyc_water[:,2] to slice this data set and get the consumption of water in millions of gallons per day yearly
# use max() function to get the maximum values
nyc_water[:,2].max()

1512.0

In [35]:
#2 How many calendar years are represented within this data set? 
# use shape[0] function to get how many rows in this dataset.
nyc_water.shape[0]

39

In [129]:
#3 What is the mean and the standard deviation of the per capita daily water consumption?
# use nyc_water[:,3] to slice this data set and get the per capita daily water consumption yearly
# use mean() function to get the mean values
print('mean: ',nyc_water[:,3].mean())
# use np.std functin to get the standard deviation
print('standard deviation ', np.std(nyc_water[:,3]))

mean:  160.30769230769232
standard deviation  31.51894330370624


In [132]:
#4 What is the increase or decrease in population from year to year?
# create a new array 'pop_diff' to store data
# use nyc_water[:,1] to slice data set and get the population yearly and store in pop_diff
pop_diff = nyc_water[:,1]
# use np.diff() function to find the increase or decrease in population from year to year
pop_diff = np.diff(pop_diff)
# print the result
pop_diff

array([-30461. ,  17602. ,  19864. ,  72119. ,  53290. ,  39540. ,
        45192. ,  23230. ,  11243. ,  -9544. ,  -8525. ,  38851. ,
        54443. ,  77222. ,  64292. ,  62582. ,  64772. ,  75631. ,
        84816. ,  89401. ,  60618. ,  16685.5,  16685.5,  16685.5,
        16685.5,  16685.5,  16685.5,  16685.5,  16685.5,  16685.5,
        16685.5, 108965. ,  77081. ,  61281. ,  49530. ,  44512. ,
        21171. ,  85025. ])